language: ruby
rvm: 2.5.1
bundler_args: --deployment
cache: bundler

env:
  matrix:
    - UNITY_VERSION="2017.1"
    - UNITY_VERSION="2017.2"
    - UNITY_VERSION="2017.3"
    - UNITY_VERSION="2017.4"
    - UNITY_VERSION="2018.1"
    - UNITY_VERSION="2018.2"
    - UNITY_VERSION="2018.3"
    - UNITY_VERSION="2019.1"

branches:
  only:
  - master

before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.10
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
script:
  - bundle exec ruby gen.rb $UNITY_VERSION > json/$UNITY_VERSION.json && ./scripts/pr-if-changed.sh
